name = "hugo-theme-pulchraCMS"
license = "MIT"
licenselink = "http://gitlab.sh.99cloud.net/v2x/v2x-cms-theme/blob/master/LICENSE"
description = "hugo-theme-pulchraCMS is a simple, minimal and responsive Portfolio Hugo Theme. hugo-theme-pulchraCMS is well organized, well-formatted and named accordingly so it’s easy to change any and all of the design. hugo-theme-pulchraCMS is built with Bootstrap 4. You can customize it very easy to fit your needs."
# homepage = "https://staticmania.com/product/hugo-theme-pulchraCMS-hugo/"
tags = ["clean", "minimal", "blog", "responsive", "personal", "google analytics", "bootstrap", "portfolio", "white", "modern", "projects", "contact form", "creative"]
features = ['bootstrap 4', 'responsive design', 'blog', 'responsive', 'minimal', 'business', 'hugo-theme', 'portfolio', 'creative', 'contact-form']
min_version = "0.41"

[author]
  name = "99cloud"
  # homepage = "https://staticmania.com/"
